package de.pincservices.graphql.api;

import org.mapstruct.InjectionStrategy;
import org.mapstruct.Mapper;
import org.mapstruct.MappingConstants;
import org.mapstruct.SubclassExhaustiveStrategy;
import org.mapstruct.SubclassMapping;

import de.pincservices.graphql.api.dto.InstrumentDTO;
import de.pincservices.graphql.api.dto.OptionDTO;
import de.pincservices.graphql.api.dto.ShareDTO;
import de.pincservices.graphql.model.Instrument;
import de.pincservices.graphql.model.Option;
import de.pincservices.graphql.model.Share;

/**
 * <p>
 * <code>subclassExhaustiveStrategy</code> has to be set to <code>RUNTIME_EXCEPTION</code> because otherwise
 * the code does not compile/the implementation classes are not generated by mapstruct but it complains
 * that InstrumentDTO is an interface.
 * </p>
 * <p>
 * Because I use constructor injection via lombok in spring beans, it has to be configured explicitly
 * here that mapstruct mapper supports that.
 * </p>
 **/
@Mapper(componentModel = MappingConstants.ComponentModel.SPRING,
        injectionStrategy = InjectionStrategy.CONSTRUCTOR,
        subclassExhaustiveStrategy = SubclassExhaustiveStrategy.RUNTIME_EXCEPTION)
public interface DTOMapper {

    @SubclassMapping(source = Share.class, target = ShareDTO.class)
    @SubclassMapping(source = Option.class, target = OptionDTO.class)
    InstrumentDTO map(Instrument instrument);
}
